# Generated by Django 4.2.20 on 2025-04-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='About Me', max_length=200),
            preserve_default=False,
        ),
    ]
